In [42]:
from PBL_DWI_lib.load_all_ConnMats import load_all_ConnMats
import numpy as np
import matplotlib.pyplot as plt

In [43]:
method = 'upper_raw'

base_path = "D:/PROCESSED_ADNI_CONTROL_GROUP/results/"
input_struct_NC = load_all_ConnMats(base_path, method)

base_path = "D:/PROCESSED_ADNI_AD_GROUP/PROCESSED_AD_GROUP/"
input_struct_AD = load_all_ConnMats(base_path, method)

x_train = np.concatenate((input_struct_NC, input_struct_AD), axis=0)
x_train.shape

(85, 247, 247, 1)

In [44]:
def rearange_ConnMats(df, num_of_parcels):
    df = np.zeros((x_train.shape[0], x_train.shape[1] * x_train.shape[2]))

    for i in range(0, x_train.shape[0], 1):
        tmp_vect = np.reshape(x_train[i, :, :, 0], newshape=(1, x_train.shape[1] * x_train.shape[2]))
        df[i, :] = tmp_vect

    col_sums = np.sum(df, axis=0)
    ind = np.argpartition(col_sums, kth=-num_of_parcels)[-num_of_parcels:]
    # col_sums[ind]

    return df[:, ind]

In [15]:
df = np.zeros((x_train.shape[0], x_train.shape[1] * x_train.shape[2]))
for i in range(0, x_train.shape[0], 1):
    tmp_vect = np.reshape(x_train[i, :, :, 0], newshape=(1, x_train.shape[1] * x_train.shape[2]))
    df[i, :] = tmp_vect

df.shape

In [31]:
col_sums = np.sum(df, axis=0)
col_sums

array([1.0712172e+07, 2.9105000e+04, 6.9411000e+04, ..., 0.0000000e+00,
       0.0000000e+00, 1.5000000e+01])

In [38]:
N = 50
ind = np.argpartition(col_sums, kth=-N)[-N:]
col_sums[ind]

array([   91679.,    94410.,    99236.,    92310.,    91939.,    99446.,
         125007.,   122549.,   137222.,   160288.,   128143.,   112201.,
         111843.,   121171.,   152488.,   100476.,   108542.,   119717.,
         162327.,   161595.,   124177.,   141268.,   134971.,   134569.,
         124046.,   159949.,   109954.,   139537.,   111894.,   153687.,
         107526.,   110126.,   102965.,   105209.,   131514.,   116419.,
         131343.,   164584.,   185707.,   207466.,   187836.,   216541.,
         279593.,   198491.,   171235.,   266100.,   409036.,   165013.,
         230098., 10712172.])

In [40]:
df[:, ind]

array([[   494.,    233.,    566., ...,   2841.,   1978., 160736.],
       [   698.,    572.,   2218., ...,   2678.,   2491., 155828.],
       [  1976.,   2151.,    863., ...,   2047.,   1912., 120925.],
       ...,
       [   684.,   2016.,   1294., ...,   1348.,   1473., 110936.],
       [  3701.,    972.,   4547., ...,    645.,    951., 146345.],
       [  1092.,    369.,    947., ...,   1052.,   5939.,  97997.]])

In [45]:
df_new = rearange_ConnMats(df, 50)
df_new

array([[   494.,    233.,    566., ...,   2841.,   1978., 160736.],
       [   698.,    572.,   2218., ...,   2678.,   2491., 155828.],
       [  1976.,   2151.,    863., ...,   2047.,   1912., 120925.],
       ...,
       [   684.,   2016.,   1294., ...,   1348.,   1473., 110936.],
       [  3701.,    972.,   4547., ...,    645.,    951., 146345.],
       [  1092.,    369.,    947., ...,   1052.,   5939.,  97997.]])